#!/bin/bash

INTERFACE_FILE=interface.hh
GIVEN_INTERFACE=plain_interface.hh
CLANG_TYPE_ERASE=$1

function generate_interface {
  ../../generate_given_interface $2 $GIVEN_INTERFACE
  mkdir -p Interface
  cp $GIVEN_INTERFACE Interface/$INTERFACE_FILE
  ./generate_interface $INTERFACE_FILE $GIVEN_INTERFACE $CLANG_TYPE_ERASE $1
}

function prepare_test_case {
  mkdir -p $1
  cp ../$1/* $1/
  python2.7 ../generate_tests.py --namespace-name $2 --class-name "Fooable" --test-file $1/interface_test.cpp --form ../interface_test.form $3
  cd $1
  generate_interface $1 $2
  cd ..
}

function prepare_vtable_test_case {
  mkdir -p $1
  cp ../$1/* $1/
  python2.7 ../generate_tests.py --namespace-name $2 --class-name "Fooable" --test-file $1/interface_test.cpp --form ../vtable_interface_test.form $3
  cd $1
  generate_interface $1 $2
  cd ..
}

# remove previously generate files
rm -rf gen/ 
mkdir -p gen
cp util.hh gen/
cp mock_fooable.hh gen/
cp non_copyable_mock_fooable.hh gen/
cd gen

# inheritance-based type-erased interfaces
prepare_test_case basic Basic
prepare_test_case basic_non_copyable BasicNonCopyable --non-copyable
prepare_test_case cow COW
prepare_test_case sbo SBO
prepare_test_case sbo_non_copyable SBONonCopyable --non-copyable
prepare_test_case sbo_cow SBO_COW

# vtable-based type-erased interfaces
prepare_vtable_test_case vtable_basic VTableBasic
prepare_vtable_test_case vtable_basic_non_copyable VTableBasicNonCopyable --non-copyable
prepare_vtable_test_case vtable_cow VTableCOW
prepare_vtable_test_case vtable_sbo VTableSBO --sbo
prepare_vtable_test_case vtable_sbo_non_copyable VTableSBONonCopyable "--sbo --non-copyable"
prepare_vtable_test_case vtable_sbo_cow VTableSBOCOW --sbo
cd ..

# run unit tests
rm -rf build && mkdir build && cd build && cmake .. && make && ./unit_tests && cd ..
